# coding: utf-8

"""
    Brainrex General Sentiment API

    Runs the price sentiment service of api.brainrex.com/sentiment/  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import brainrex
from brainrex.models.text2 import Text2  # noqa: E501
from brainrex.rest import ApiException


class TestText2(unittest.TestCase):
    """Text2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testText2(self):
        """Test Text2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = brainrex.models.text2.Text2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
