# coding: utf-8

"""
    Brainrex General Sentiment API

    Runs the price sentiment service of api.brainrex.com/sentiment/  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import brainrex
from brainrex.api.anomaly_api import AnomalyApi  # noqa: E501
from brainrex.rest import ApiException


class TestAnomalyApi(unittest.TestCase):
    """AnomalyApi unit test stubs"""

    def setUp(self):
        self.api = brainrex.api.anomaly_api.AnomalyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_anomaly_batch(self):
        """Test case for anomaly_batch

        Detects anomaly in historical data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
