# coding: utf-8

"""
    Brainrex General Sentiment API

    Runs the price sentiment service of api.brainrex.com/sentiment/  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import brainrex
from brainrex.models.candle_response import CandleResponse  # noqa: E501
from brainrex.rest import ApiException


class TestCandleResponse(unittest.TestCase):
    """CandleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCandleResponse(self):
        """Test CandleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = brainrex.models.candle_response.CandleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
