# coding: utf-8

"""
    Brainrex General Sentiment API

    Runs the price sentiment service of api.brainrex.com/sentiment/  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import brainrex
from brainrex.models.text1 import Text1  # noqa: E501
from brainrex.rest import ApiException


class TestText1(unittest.TestCase):
    """Text1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testText1(self):
        """Test Text1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = brainrex.models.text1.Text1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
