# coding: utf-8

"""
    Brainrex API

    Provides anomaly detection and natural language processing technlogies to blockchain developers.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "brainrex"
VERSION = "0.9.4"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="Brainrex API",
    author_email="",
    url="https://github.com/BrainrexAPI/brainrex-python",
    keywords=["Swagger", "Brainrex API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Provides anomaly detection and natural language processing technlogies to blockchain developers.  # noqa: E501
    """
)
